[package]
name = "string-escape-simd"
version = "0.1.0"
edition = "2021"

[features]
nightly = [] # For benchmark
default = []

[[example]]
name = "escape"
path = "examples/escape.rs"

[[bench]]
name = "escape"
harness = false

[dependencies]
anyhow = "1"

[dev-dependencies]
criterion = { version = "0.7", features = ["html_reports"] }
serde_json = "1"
v_jsonescape = "0.7"

[profile.bench]
lto = true
codegen-units = 1

[profile.instruments]
inherits = "release"
lto = false
debug = true