[package]
name = "string-escape-simd"
version = "0.1.0"
edition = "2021"

[features]
nightly = [] # For benchmark
default = []

[[bin]]
name = "affine_bench"
path = "src/bin/affine_bench.rs"

[[example]]
name = "escape"
path = "examples/escape.rs"

[[example]]
name = "v8_demo"
path = "examples/v8_demo.rs"

[[bench]]
name = "escape"
harness = false

[dependencies]
anyhow = "1"
serde = "1"
serde_json = "1"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[profile.bench]
lto = true
codegen-units = 1

[profile.instruments]
inherits = "release"
lto = false
debug = true