[package]
name = "string-escape-simd"
version = "0.1.0"
edition = "2021"

[features]
nightly = [] # For benchmark
default = []

[dependencies]
anyhow = "1"

[dev-dependencies]
serde_json = "1"

[profile.bench]
lto = true