name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bench:
    strategy:
      matrix:
        settings:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-24.04-arm
          - target: aarch64-pc-windows-msvc
            os: windows-11-arm
          - target: aarch64-apple-darwin
            os: macos-latest
      fail-fast: false
    runs-on: ${{ matrix.settings.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.settings.target }}
        env:
          CARGO_INCREMENTAL: '1'
      - name: Run benchmarks
        run: cargo bench
        env:
          RUSTFLAGS: '-C target-cpu=native'