name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bench:
    strategy:
      matrix:
        settings:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
      fail-fast: false
    runs-on: ${{ matrix.settings.os }}
    steps:
      - uses: actions/checkout@v5
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.settings.target }}
      - name: Run benchmarks
        run: cargo bench
        env:
          RUSTFLAGS: '-C target-cpu=native'